### ISSUE TITLE
Technical Blog Post (12/14)

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/blog#40]
**What is the goal of the post and why does it need to be written?**
A clear and concise goal statement of the post and why it should be published. E.g. "To educate developers of the challenges of building real-time data pipelines, and how using Spice.ai makes it easier."

**What is the intent of the post?**
Inform | Describe | Convince | Tell a story

**Target Audience**
A precise target audience. E.g. Professional developer | Web3 developer | Spice.ai Project Contributor | Potential customer.

**Draft Outline**
A rough outline of the post.

**Comment by Corentin-pro** [comment]
Illustrations:

![branching_td](https://user-images.githubusercontent.com/19952490/145569828-f9505a88-1556-4c88-ba43-834daa60e594.png)
![maze_values](https://user-images.githubusercontent.com/19952490/145569835-ff21b42f-21d0-4eb3-a451-9b9aa5a76f78.png)
![neural_network_q_estimator](https://user-images.githubusercontent.com/19952490/145569840-369d4eb0-48c6-44d8-bc5e-bfabdd7713a4.png)
![q_table](https://user-images.githubusercontent.com/19952490/145569842-298103e3-e7ed-412f-8229-66c745d29807.png)
![q_values](https://user-images.githubusercontent.com/19952490/145569847-4be91c13-3ffb-4ad8-83c4-fb841e9d2c96.png)
![simple_td](https://user-images.githubusercontent.com/19952490/145569849-f528b7df-a240-41d6-b850-fde58334cac5.png)
![td_0_propagation](https://user-images.githubusercontent.com/19952490/145569853-335f65d9-aa16-44c6-9e97-287db5862628.png)
