### ISSUE TITLE
Real-time application data classes blog post (12/23)

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/blog#45]
**What is the goal of the post and why does it need to be written?**

To educate developers on the three classes of data required to build real-time AI-driven applications and how Spice.ai helps with all three.

**What is the intent of the post?**

Inform

**Target Audience**

Potential users (developers) of Spice.ai. Professional application developers.

**Draft Outline**

Building real-time AI-driven applications require three classes of data being real-time data, personalized historical data, and global historical data. All three need to be processed into the same AI-ready format. Spice.ai helps capture and process all three and delivers to both the application and AI engine.

**Will acknowledge but not discuss**

- Training/validation data.

**Comment by lukekim** [comment]
Published!
