### ISSUE TITLE
Blog post - Spice.ai's SACD implementation (1/6)

### ISSUE THREAD

**Issue by lukekim** [spiceai/blog#54]

**Comment by Corentin-pro** [comment]
What:
Describing and explaining Soft Actor-Critic and how it was added to Spice.ai.

Why:
Understand to pros and cons of the algorithm, why this is an interesting addition to the platform and showing how easy it is to add agent.

Images:
![actor_critic](https://user-images.githubusercontent.com/19952490/148524970-e5fab55c-7364-4cb9-870c-7f5b8b58cc6f.png)
